steps:
  # - label: "🏠"
  #   command: "echo $$HOME"
  - label: "🧑‍🔬 All tests"
    command: "./.buildkite/all_tests.sh"
    plugins:
      - docker#v5.3.0:
          image: "golang:latest"
          runtime: "runsc"
      - test-collector#v1.0.0:
          files: "junit.xml"
          format: "junit"